language: c

compiler:
  - gcc
  - clang

os:
  - linux
  - osx

script: 
  - ./build.sh
  - ./test/generate-xml.sh test/test-frames
  - ./test/generate-xml.sh test/error-frames || true
  - ./test/generate-xml.sh test/unsupported-frames || true
